sae:
  d_in: 1024
  d_sae: 1024
  architecture: "topk"
  activation_fn_str: "topk"
  activation_fn_kwargs:
    k: 20
    postact_fn_str: "relu"
  lr: 0.0005
  lr_end_factor: 0.0
  lr_scheduler_name: null
  lr_warm_up_steps: 500
  train_batch_size: 64
  clip_gradients: false
  dead_feature_window: 1000
  topk_aux_loss_coefficient: 2.0
  aux_k: null
  l1_coefficient: 0.0
  initial_l1_coefficient: 0.0
  l1_warm_up_steps: 1000
  embedding_source_name: "fitzpatrick17k"
  eval_batch_size: 32
  eval_interval_steps: 1000
  eval_n_batches: 50
  log_to_wandb: true
  wandb_dir: "./experiments"
  wandb_project: "thesis"
  wandb_entity: "voerik"
  wandb_run_name: "dinov3_topk_1024_expansion_10"
  wandb_log_frequency_steps: 500
  n_checkpoints: 5
  checkpoint_path: "./checkpoints/"

activation_store:
  dataset_name: "fitzpatrick17k"
  eval_dataset_name: "skincon_fitzpatrick17k"
  dataset_path: "./data/"
  embedding_cache_path: "./embeddings"
  extraction_batch_size: 64
  dtype: "torch.float32"
  feature_extractor: "dinov3_vitl16"